---
-  name: test
   hosts: all
   tasks:
   - name: git check
     command: git --version
     register: output
   - debug:
        var: output

   - name: docker
     script: ./docker_run.sh
     become: yes
     become_user: root
   - debug:
        var: output
